project:
  type: book
  output-dir: _book

execute-dir: project

lang: it

resources:
  - widgets/**

book:
  title: "Elementi di computazione"
  subtitle: "Per il corso di Laboratorio di Fisica"
  author: "Luca Baldini"

  site-url: https://unipi-physics-labs.github.io/lab1-computing/
  repo-url: https://github.com/unipi-physics-labs/lab1-computing
  repo-actions: [edit, issue]

  page-footer:
    left: |
      © 2026 Luca Baldini.
      Rilasciato sotto licenza
      [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.it).

  search: true

  chapters:
    - index.qmd
    - copyright.qmd
    - gender.qmd
    - foss.qmd

    - part: "Parte prima: dal problema alla soluzione"
      chapters:
        - chapters/install.qmd
        - chapters/crash.qmd
        - chapters/types.qmd
        - chapters/functions.qmd
        - chapters/flow.qmd

    - part: "Parte seconda: ripartiamo dai principi"
      chapters:
        - chapters/count.qmd
        - chapters/hw.qmd
        - chapters/os.qmd
        - chapters/memory.qmd
        - chapters/float.qmd
        - chapters/algs.qmd
        - chapters/vec.qmd

  appendices:
    - appendices/latex.qmd

bibliography: references.bib

execute:
  freeze: false
  echo: true
  warning: true

format:
  html:
    theme:
      - cosmo
      - styles/custom.scss
    default-image-extension: svg
    code-copy: true
    code-link: true
    code-fold: false
    toc: true
    toc-depth: 3

  pdf:
    default-image-extension: pdf

jupyter: python3