# Nota sul linguaggio di genere {.unnumbered #sec-gender}

Care studentesse, in barba alle regole della grammatica italiana, queste note sono
scritte utilizzando il *femminile sovraesteso*. Questo vuol dire che quando dico
"care studentesse" intendo quello che solitamente si scriverebbe "cari studenti"
(con il maschile non marcato) e che, utilizzando un linguaggio di genere si potrebbe
esprimere in modo meno compatto scrivendo "care/i studentesse/studenti", o
variazioni sul tema.

Sono consapevole che questa scelta non sia condivisa dalla maggior parte delle
linguiste[^1], e capisco pienamente le motivazioni. Si tratta di un problema complesso
che non ha una soluzione ovvia, e questa piccola iniziativa non ha nessuna pretesa di
costituire un contributo originale alla discussione---è, molto più modestamente,
un tentativo maldestro di fare *qualcosa*, nella convinzione che non fare niente sia
peggio.

Spero che nessuna si senta offesa, e che se questa scelta genera un qualche tipo
di discussione---magari durante l'aperitivo del venerdì sera---questa discussione
serva a far sì che l'ambiente in cui viviamo e lavoriamo diventi veramente un posto
in cui tutte (e tutti) si sentono benvenuti.


[^1]: Consiglio a tutte la lettura di questo bell'[articolo](https://accademiadellacrusca.it/it/consulenza/mettiamo-tutto-e-tutti-al-femminile/30517)
dell'Accademia della Crusca.