# Cronologia delle versioni {#sec-history}

* Primo draft del capitolo sui formati grafici
  ([PR 9](https://github.com/unipi-physics-labs/lab1-computing/pull/9))
* Revisione completa del capitolo sull'istallazione di Python e dell'ecosistema
  ([PR 8](https://github.com/unipi-physics-labs/lab1-computing/pull/8))
* Primo draft del capitolo sulla vettorizzazione
  ([PR 7](https://github.com/unipi-physics-labs/lab1-computing/pull/7))
* Figure rigenerate disabilitando il tema xkcd
  ([PR 6](https://github.com/unipi-physics-labs/lab1-computing/pull/6))


### Versione 0.5.0 (2026-08-27) {.unnumbered}

* Prima versione completa del capitolo sul controllo del flusso.
* Prima versione completa del glossario.
* Piccoli cambiamenti quà e là.


### Versione 0.4.5 (2026-08-22) {.unnumbered}

* Bug fix nell'import dei moduli JS.
* Non ci sono cambiamenti al testo delle note.


### Versione 0.4.4 (2026-08-22) {.unnumbered}

* Piccolo bug fix nel README.
* Non ci sono cambiamenti al testo delle note.


### Versione 0.4.3 (2026-08-22) {.unnumbered}

* Nome del file pdf cambiato in "compnotes".
* Script di release modificato per generare il README aggiornato.
* Non ci sono cambiamenti al testo delle note.


### Versione 0.4.2 (2026-08-21) {.unnumbered}

* Piccolo fix.
* Non ci sono cambiamenti al testo delle note.


### Versione 0.4.1 (2026-08-21) {.unnumbered}

* Percorso al file di metadati corretto.
* Non ci sono cambiamenti al testo delle note.


### Versione 0.4.0 (2026-08-21) {.unnumbered}

* Compilazione del pdf statico per la sezione delle release.
* Non ci sono cambiamenti al testo delle note.


### Versione 0.3.2 (2026-08-21) {.unnumbered}

* Creazione del pdf compilato temporaneamente disabilitata per cercare di avere
  l'html statico su github pages.
* Non ci sono cambiamenti al testo delle note.


### Versione 0.3.1 (2026-08-21) {.unnumbered}

* Tweak di pyproject.toml per l'istallazione del pacchetto per la pubblicazione.
* Non ci sono cambiamenti al testo delle note.


### Versione 0.3.0 (2026-08-21) {.unnumbered}

* Prima versione pubblicata su github pages.
* Non ci sono cambiamenti al testo delle note.


### Versione 0.2.0 (2026-08-21) {.unnumbered}

* Versione iniziale di un semplice release manager.
* Non ci sono cambiamenti al testo delle note.


### Versione 0.1.0 {.unnumbered}

* Versione iniziale, con tutto il materiale delle vecchie note in LaTeX, ed un
  certo numero di aggiunte.
* Ancora un work in progress, con intere sezioni incomplete.